[package]
name = "coloring-bt-transactions"
version = "0.1.0"
edition = "2021"

[dependencies]
webgraph = { git = "https://github.com/vigna/webgraph-rs.git" }
non-layered-tidy-trees = { git = "https://github.com/massimo-nocentini/non-layered-tidy-trees-rs.git" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
